### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by melanierichards** [melanierichards/bucketlist#7]
# Launch checklist

## Content

* [x] All content filled in, spelled correctly, etc.
* [x] [No broken links](https://validator.w3.org/checklink)
* [x] If responsive images used, no broken sources at all browser widths/pixel densities

## Styling

* [x] User highlight styles
* [x] Focus state

## Head content

* [x] Keywords, description, title
* [x] Change robots back to index, follow
* [x] Favicons

## General testing

* [x] [HTML5 validator](https://html5.validator.nu/)

## Accessibility

* [x] Keyboard accessible
* [x] [Webaim WCAG 2.0 checklist](http://webaim.org/standards/wcag/checklist)

## Etc 

* [x] 404 page, any other status pages are in place

**Comment by melanierichards** [comment]
🎉
